import type { ChatMessage, ConversationSummary } from '../src/chat/types';
import type { PrometheonViewState } from '../src/core/state';
import { CLAUDE_MODELS } from '../src/providers/types';

/**
 * Estado de exemplo do preview: um workspace saudável, conectado ao Hub, com
 * uma conversa em andamento — o suficiente para cada canto do painel ter o que
 * mostrar. Nada aqui é real; datas são relativas ao carregamento para as
 * idades ("há 2 horas") nunca envelhecerem.
 */

const NOW = Date.now();
const MINUTES = 60_000;

const CONVERSATION_ID = 'preview-conversation';

const MESSAGES: readonly ChatMessage[] = [
  {
    id: 'm1',
    conversationId: CONVERSATION_ID,
    author: 'user',
    content: 'Adicione o seletor de autonomia ao composer e cubra com testes.',
    status: 'sent',
    timestamp: NOW - 42 * MINUTES,
  },
  {
    id: 'm2',
    conversationId: CONVERSATION_ID,
    author: 'agent',
    agentId: 'claude-code',
    agentName: 'Claude Code',
    content:
      'Seletor adicionado ao composer, com os três níveis e persistência no estado local. Os testes cobrem a troca de nível e o bloqueio do bypass sem confirmação.',
    steps: [
      {
        id: 's1',
        kind: 'thought',
        tool: 'Thinking',
        title: 'Mapping the composer layout',
        status: 'done',
        startedAt: NOW - 41 * MINUTES,
        durationMs: 9_000,
      },
      {
        id: 's2',
        kind: 'tool',
        tool: 'Read',
        title: 'src/views/webview/main.ts',
        detail: '5,520 lines',
        status: 'done',
        startedAt: NOW - 40 * MINUTES,
        durationMs: 2_000,
      },
      {
        id: 's3',
        kind: 'tool',
        tool: 'Edit',
        title: 'src/views/webview/main.ts',
        detail: 'autonomy selector wired to state',
        edit: {
          removed: "const autonomy = 'auto';\nreturn autonomy;",
          added: "const autonomy = state.autonomy;\nreturn autonomy;",
        },
        status: 'done',
        startedAt: NOW - 38 * MINUTES,
        durationMs: 4_000,
      },
      {
        id: 's4',
        kind: 'tool',
        tool: 'Bash',
        title: 'npm test',
        command: 'cd "F:/Projects/Prometheon/extension" && npm test -- --reporter spec',
        output: '  223 passing (22s)\n',
        outputLines: 1,
        status: 'done',
        startedAt: NOW - 35 * MINUTES,
        durationMs: 180_000,
      },
    ],
    usage: { input: 48_200, output: 3_900 },
    status: 'sent',
    timestamp: NOW - 34 * MINUTES,
  },
];

const SESSIONS: readonly ConversationSummary[] = [
  {
    id: CONVERSATION_ID,
    title: 'Seletor de autonomia',
    chatType: 'local',
    createdAt: NOW - 50 * MINUTES,
    updatedAt: NOW - 34 * MINUTES,
    messageCount: 2,
  },
  {
    id: 'preview-older-1',
    title: 'Refatorar o SecretStore',
    chatType: 'local',
    createdAt: NOW - 26 * 60 * MINUTES,
    updatedAt: NOW - 25 * 60 * MINUTES,
    messageCount: 14,
  },
  {
    id: 'preview-older-2',
    title: 'Bug do badge do Hub',
    chatType: 'local',
    createdAt: NOW - 3 * 24 * 60 * MINUTES,
    updatedAt: NOW - 3 * 24 * 60 * MINUTES,
    messageCount: 6,
  },
];

export const PREVIEW_STATE: PrometheonViewState = {
  extensionVersion: '0.0.1',
  language: 'pt-br',
  chatType: 'local',
  workMode: 'edit',
  autonomy: 'auto',
  bypass: null,
  mainAgentId: 'claude-code',
  agents: [
    { id: 'claude-code', displayName: 'Claude Code', transport: 'cli', available: true },
    { id: 'mock', displayName: 'Mock Agent', transport: 'mock', available: true },
  ],
  activeAgents: [
    {
      sessionId: 'sess-1',
      agentId: 'claude-code',
      displayName: 'Claude Code',
      role: 'main',
      status: 'idle',
      task: null,
    },
    // Um worker vivo, com o que a aba dele precisa exercitar: diff de edição,
    // comando com resultado, a conversa direta e uma mensagem esperando a vez.
    {
      sessionId: 'sess-worker-1',
      agentId: 'claude-code',
      displayName: 'Pisk Programador',
      role: 'worker',
      status: 'working',
      roleLabel: 'Implementer',
      engine: 'Claude Code',
      model: 'claude-opus-5',
      task: 'Acrescentar navegação lateral e o catálogo de itens',
      talkable: true,
      queued: ['Antes de seguir, confere se o painel abre sem backend.'],
      messages: [
        {
          role: 'user',
          text: 'Usa a rota `/api/server` que o James já criou, não inventa outra.',
          at: NOW - 6 * MINUTES,
        },
        {
          role: 'agent',
          text: 'Certo — troquei o fetch para `/api/server` e removi o mock.',
          at: NOW - 5 * MINUTES,
        },
      ],
      steps: [
        {
          id: 'w1',
          sessionId: 'sess-worker-1',
          kind: 'tool',
          tool: 'Edit',
          title: 'next.config.mjs',
          edit: {
            removed: "  trailingSlash: false,\n  output: 'standalone',",
            added: "  trailingSlash: true,\n  output: 'export',\n  images: { unoptimized: true },",
          },
          status: 'done',
          startedAt: NOW - 8 * MINUTES,
          durationMs: 1_200,
        },
        {
          id: 'w2',
          sessionId: 'sess-worker-1',
          kind: 'tool',
          tool: 'Bash',
          title: 'cd "F:/Projects/Rust/.prometheon/worktrees/pisk-programador-wt-9e918e39…',
          detail: 'Check node_modules and node availability',
          command:
            'cd "F:/Projects/Rust/.prometheon/worktrees/pisk-programador-wt-9e918e39" && ls node_modules/.bin | head -20',
          output: 'next\nnext-env\ntsc\ntsserver\neslint\nprettier\n',
          outputLines: 6,
          status: 'done',
          startedAt: NOW - 7 * MINUTES,
          durationMs: 3_400,
        },
      ],
    },
  ],
  hub: { state: 'connected', detail: 'Conectado como Mateuus' },
  webProjects: [
    { id: 'proj-1', name: 'Prometheon' },
    { id: 'proj-2', name: 'Origin Interactive' },
  ],
  webProjectId: 'proj-1',
  speech: { available: true, state: 'idle' },
  accounts: [
    {
      profileId: 'acct-claude',
      name: 'Pessoal',
      providerId: 'claude-code',
      providerName: 'Claude Code',
      configDirectory: '~/.prometheon/providers/claude-code/pessoal',
      model: 'claude-fable-5',
      cliInstalled: true,
      cliVersion: '2.1.220',
      authenticated: true,
      accountLabel: 'mateus@prometheoncode.xyz',
      plan: 'Max',
      authMethod: 'OAuth',
      usage: {
        today: { input: 182_000, output: 24_500 },
        last7Days: { input: 1_450_000, output: 210_000 },
        total: { input: 9_800_000, output: 1_320_000 },
        runs: 87,
        lastRunAt: NOW - 34 * MINUTES,
      },
    },
  ],
  providers: [
    {
      id: 'claude-code',
      name: 'Claude Code',
      configEnvironmentVariable: 'CLAUDE_CONFIG_DIR',
    },
  ],
  models: [{ providerId: 'claude-code', models: CLAUDE_MODELS }],
  agentProfiles: [
    {
      profile: {
        id: 'profile-main',
        name: 'Orquestrador',
        providerProfileId: 'acct-claude',
        role: 'orchestrator',
        model: 'claude-fable-5',
        autonomyMode: 'auto',
        allowedTools: [],
        deniedTools: [],
        skills: ['plan'],
        maxConcurrentSessions: 4,
        contextStrategy: 'project',
        enabled: true,
      },
      providerName: 'Claude Code',
      accountName: 'Pessoal',
      accountAuthenticated: true,
      customRole: null,
    },
    {
      profile: {
        id: 'profile-tester',
        name: 'Gameplay Tester',
        providerProfileId: 'acct-claude',
        role: 'custom',
        customRoleId: 'gameplay-pie-ue5-test',
        autonomyMode: 'manual',
        allowedTools: [],
        deniedTools: ['Bash'],
        skills: [],
        maxConcurrentSessions: 1,
        contextStrategy: 'isolated',
        enabled: true,
      },
      providerName: 'Claude Code',
      accountName: 'Pessoal',
      accountAuthenticated: true,
      customRole: {
        id: 'gameplay-pie-ue5-test',
        label: 'Gameplay PIE UE5 Test',
        description: 'Valida gameplay em Play-In-Editor no UE5.',
        basedOn: 'tester',
        skills: ['test-driven-development'],
        scope: 'project',
      },
    },
  ],
  customRoles: [
    {
      id: 'gameplay-pie-ue5-test',
      label: 'Gameplay PIE UE5 Test',
      description: 'Valida gameplay em Play-In-Editor no UE5.',
      basedOn: 'tester',
      skills: ['test-driven-development'],
      scope: 'project',
    },
  ],
  skills: {
    skills: [
      {
        name: 'plan',
        title: 'Plan before touching code',
        description: 'Breaks a task down before anything is edited.',
        category: 'workflow',
        scope: 'project',
        riskLevel: 'none',
        version: '1.2.0',
        license: 'MIT',
        author: 'Prometheon',
        platforms: [],
        requiresMcp: [],
        autonomyCeiling: 'auto',
        bodyTokensEstimate: 1_800,
        supportFiles: [],
        path: '.prometheon/skills/plan/SKILL.md',
        supported: true,
      },
      {
        name: 'test-driven-development',
        title: 'Test-driven development',
        description: 'Red, green, refactor — in that order.',
        category: 'engineering',
        scope: 'machine',
        riskLevel: 'low',
        version: '2.0.1',
        license: 'MIT',
        author: 'Prometheon',
        platforms: [],
        requiresMcp: [],
        autonomyCeiling: 'auto',
        bodyTokensEstimate: 3_400,
        supportFiles: ['references/patterns.md'],
        path: '~/.prometheon/skills/test-driven-development/SKILL.md',
        supported: true,
      },
    ],
    problems: [],
    roots: ['.prometheon/skills', '~/.prometheon/skills', '.claude/skills'],
  },
  mcp: {
    available: true,
    exists: true,
    file: '.mcp.json',
    servers: [
      {
        name: 'loreforge',
        transport: 'stdio',
        command: 'npx',
        args: ['-y', '@loreforge/mcp'],
        env: [],
        headers: [],
        enabled: true,
        preservedFields: [],
        warnings: [],
      },
    ],
    problems: [],
  },
  graph: {
    available: true,
    enabled: true,
    outputDir: '.prometheon/graph',
    exists: true,
    ageMs: 2 * 60 * MINUTES,
    rebuildCommand: 'graphify build',
    rebuildOn: 'commit',
    gate: '',
    blockOnHygieneFailure: false,
    cliDetected: true,
  },
  git: {
    available: true,
    coAuthoredBy: false,
    commitStyle: 'conventional',
    commitLanguage: 'pt-br',
    scopes: ['extension', 'hub', 'docs', 'ci', 'scripts', 'repo'],
    hooksInstalled: true,
    hooksPath: null,
  },
  activity: { phase: 'idle', label: '', startedAt: null },
  context: {
    usedTokens: 342_000,
    windowTokens: 1_000_000,
    autoCompact: true,
    threshold: 0.85,
    modelLabel: 'Fable 5',
  },
  workspace: {
    configured: true,
    folderName: 'Prometheon',
    hasGit: true,
    externalFolder: null,
    skipped: false,
  },
  conversationId: CONVERSATION_ID,
  conversationTitle: 'Seletor de autonomia',
  messages: MESSAGES,
  sessions: SESSIONS,
  busy: false,
  queued: [],
  pendingQuestion: null,
};
